const primitiveColors = Object.freeze({
  gray50: '#f8fafc',
  gray100: '#eef2f6',
  gray200: '#d8dee8',
  gray300: '#bcc6d3',
  gray500: '#667085',
  gray600: '#475467',
  gray700: '#344054',
  gray800: '#1f2937',
  gray900: '#111827',
  blue500: '#2f6fed',
  blue600: '#245bd4',
  green600: '#16845b',
  amber600: '#b76e00',
  red600: '#c93434',
  red700: '#a82222',
  white: '#ffffff'
});

const primitiveSpacing = Object.freeze({
  space2Px: 2,
  space4Px: 4,
  space6Px: 6,
  space8Px: 8,
  space10Px: 10,
  space12Px: 12,
  space16Px: 16,
  space20Px: 20,
  space24Px: 24,
  space32Px: 32
});

const primitiveRadii = Object.freeze({
  controlPx: 6,
  panelPx: 8,
  dialogPx: 10
});

const primitiveTypography = Object.freeze({
  fontFamily:
    'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  fontSizeXsPx: 11,
  fontSizeSmPx: 12,
  fontSizeBasePx: 13,
  fontSizeMdPx: 14,
  fontSizeLgPx: 18,
  lineHeightTight: 1.25,
  lineHeightBase: 1.45
});

export const DESIGN_TOKENS = Object.freeze({
  color: Object.freeze({
    appBackground: primitiveColors.gray100,
    surface: primitiveColors.white,
    surfaceSubtle: primitiveColors.gray50,
    surfaceRaised: primitiveColors.white,
    border: primitiveColors.gray200,
    borderStrong: primitiveColors.gray300,
    textPrimary: primitiveColors.gray900,
    textSecondary: primitiveColors.gray600,
    textMuted: primitiveColors.gray500,
    action: primitiveColors.blue500,
    actionHover: primitiveColors.blue600,
    actionWeak: '#e8f0ff',
    success: primitiveColors.green600,
    successWeak: '#ecfdf5',
    successBorder: '#a8e6c8',
    warning: primitiveColors.amber600,
    warningWeak: '#fff8e7',
    warningBorder: '#f5d28a',
    danger: primitiveColors.red600,
    dangerHover: primitiveColors.red700,
    dangerWeak: '#fff1f1',
    dangerBorder: '#f0a5a5',
    focusRing: '#8bb5ff',
    locked: primitiveColors.gray700,
    dirty: primitiveColors.amber600,
    overlayBackdrop: 'rgb(17 24 39 / 32%)'
  }),
  spacing: primitiveSpacing,
  radius: primitiveRadii,
  typography: primitiveTypography,
  elevation: Object.freeze({
    dialog: '0 18px 52px rgb(17 24 39 / 18%)',
    popover: '0 10px 28px rgb(17 24 39 / 12%)'
  }),
  size: Object.freeze({
    sidebarWidthPx: 304,
    toolbarHeightPx: 48,
    controlHeightPx: 32,
    compactControlHeightPx: 28,
    iconButtonHeightPx: 30,
    statusPillRadiusPx: 999,
    emptyStateMinHeightPx: 220,
    fileStatusColumnWidthPx: 42,
    historyShaColumnWidthPx: 86,
    historyShaColumnCompactWidthPx: 72,
    historyMetaMinWidthPx: 160,
    dialogMaxWidthPx: 520,
    minAppWidthPx: 860
  })
});

export const DESIGN_TOKEN_CSS_VARIABLES = Object.freeze({
  '--color-app-background': DESIGN_TOKENS.color.appBackground,
  '--color-surface': DESIGN_TOKENS.color.surface,
  '--color-surface-subtle': DESIGN_TOKENS.color.surfaceSubtle,
  '--color-surface-raised': DESIGN_TOKENS.color.surfaceRaised,
  '--color-border': DESIGN_TOKENS.color.border,
  '--color-border-strong': DESIGN_TOKENS.color.borderStrong,
  '--color-text-primary': DESIGN_TOKENS.color.textPrimary,
  '--color-text-secondary': DESIGN_TOKENS.color.textSecondary,
  '--color-text-muted': DESIGN_TOKENS.color.textMuted,
  '--color-action': DESIGN_TOKENS.color.action,
  '--color-action-hover': DESIGN_TOKENS.color.actionHover,
  '--color-action-weak': DESIGN_TOKENS.color.actionWeak,
  '--color-success': DESIGN_TOKENS.color.success,
  '--color-success-weak': DESIGN_TOKENS.color.successWeak,
  '--color-success-border': DESIGN_TOKENS.color.successBorder,
  '--color-warning': DESIGN_TOKENS.color.warning,
  '--color-warning-weak': DESIGN_TOKENS.color.warningWeak,
  '--color-warning-border': DESIGN_TOKENS.color.warningBorder,
  '--color-danger': DESIGN_TOKENS.color.danger,
  '--color-danger-hover': DESIGN_TOKENS.color.dangerHover,
  '--color-danger-weak': DESIGN_TOKENS.color.dangerWeak,
  '--color-danger-border': DESIGN_TOKENS.color.dangerBorder,
  '--color-focus-ring': DESIGN_TOKENS.color.focusRing,
  '--color-locked': DESIGN_TOKENS.color.locked,
  '--color-dirty': DESIGN_TOKENS.color.dirty,
  '--color-overlay-backdrop': DESIGN_TOKENS.color.overlayBackdrop,
  '--space-2': `${DESIGN_TOKENS.spacing.space2Px}px`,
  '--space-4': `${DESIGN_TOKENS.spacing.space4Px}px`,
  '--space-6': `${DESIGN_TOKENS.spacing.space6Px}px`,
  '--space-8': `${DESIGN_TOKENS.spacing.space8Px}px`,
  '--space-10': `${DESIGN_TOKENS.spacing.space10Px}px`,
  '--space-12': `${DESIGN_TOKENS.spacing.space12Px}px`,
  '--space-16': `${DESIGN_TOKENS.spacing.space16Px}px`,
  '--space-20': `${DESIGN_TOKENS.spacing.space20Px}px`,
  '--space-24': `${DESIGN_TOKENS.spacing.space24Px}px`,
  '--space-32': `${DESIGN_TOKENS.spacing.space32Px}px`,
  '--radius-control': `${DESIGN_TOKENS.radius.controlPx}px`,
  '--radius-panel': `${DESIGN_TOKENS.radius.panelPx}px`,
  '--radius-dialog': `${DESIGN_TOKENS.radius.dialogPx}px`,
  '--font-family-base': DESIGN_TOKENS.typography.fontFamily,
  '--font-size-xs': `${DESIGN_TOKENS.typography.fontSizeXsPx}px`,
  '--font-size-sm': `${DESIGN_TOKENS.typography.fontSizeSmPx}px`,
  '--font-size-base': `${DESIGN_TOKENS.typography.fontSizeBasePx}px`,
  '--font-size-md': `${DESIGN_TOKENS.typography.fontSizeMdPx}px`,
  '--font-size-lg': `${DESIGN_TOKENS.typography.fontSizeLgPx}px`,
  '--line-height-tight': `${DESIGN_TOKENS.typography.lineHeightTight}`,
  '--line-height-base': `${DESIGN_TOKENS.typography.lineHeightBase}`,
  '--elevation-dialog': DESIGN_TOKENS.elevation.dialog,
  '--elevation-popover': DESIGN_TOKENS.elevation.popover,
  '--size-sidebar-width': `${DESIGN_TOKENS.size.sidebarWidthPx}px`,
  '--size-toolbar-height': `${DESIGN_TOKENS.size.toolbarHeightPx}px`,
  '--size-control-height': `${DESIGN_TOKENS.size.controlHeightPx}px`,
  '--size-compact-control-height': `${DESIGN_TOKENS.size.compactControlHeightPx}px`,
  '--size-icon-button-height': `${DESIGN_TOKENS.size.iconButtonHeightPx}px`,
  '--size-status-pill-radius': `${DESIGN_TOKENS.size.statusPillRadiusPx}px`,
  '--size-empty-state-min-height': `${DESIGN_TOKENS.size.emptyStateMinHeightPx}px`,
  '--size-file-status-column-width': `${DESIGN_TOKENS.size.fileStatusColumnWidthPx}px`,
  '--size-history-sha-column-width': `${DESIGN_TOKENS.size.historyShaColumnWidthPx}px`,
  '--size-history-sha-column-compact-width': `${DESIGN_TOKENS.size.historyShaColumnCompactWidthPx}px`,
  '--size-history-meta-min-width': `${DESIGN_TOKENS.size.historyMetaMinWidthPx}px`,
  '--size-dialog-max-width': `${DESIGN_TOKENS.size.dialogMaxWidthPx}px`,
  '--size-min-app-width': `${DESIGN_TOKENS.size.minAppWidthPx}px`
});

export type DesignTokenCssVariableName = keyof typeof DESIGN_TOKEN_CSS_VARIABLES;
